# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0002_auto_20160427_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='middle_initial',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
