# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0004_auto_20160427_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightkeywords',
            name='list_of_lessons',
            field=models.TextField(default=datetime.datetime(2016, 4, 27, 20, 50, 31, 69815, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
