# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0006_auto_20160427_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('icon_url', models.CharField(max_length=255)),
            ],
        ),
    ]
