# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0007_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_authors', to='inspiration.Author'),
        ),
        migrations.AlterField(
            model_name='wordstoignore',
            name='word',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
