# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medium',
            name='cover',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medium',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
