# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0003_author_middle_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
