# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0005_auto_20160523_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='contributors',
        ),
        migrations.AddField(
            model_name='medium',
            name='medium_contributors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='inspiration.MediumContribution'),
        ),
    ]
