# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0007_auto_20160523_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='medium_contributors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspiration.MediumContribution'),
        ),
    ]
