# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0008_auto_20160524_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediumcontribution',
            name='medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspiration.Medium'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='medium_contributors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medium_contributors', to='inspiration.MediumContribution'),
        ),
    ]
