# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 03:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0010_auto_20160524_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='medium_contributors',
        ),
        migrations.AddField(
            model_name='mediumcontribution',
            name='medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspiration.Medium'),
            preserve_default=False,
        ),
    ]
