# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0012_auto_20160524_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumcontribution',
            name='medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='inspiration.Medium'),
        ),
    ]
