# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import inspiration.models.InspirationBaseModelMixin


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0014_auto_20160526_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediumLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(null=True)),
                ('medium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='inspiration.Medium')),
            ],
            bases=(models.Model, inspiration.models.InspirationBaseModelMixin.InspirationBaseModelMixIn),
        ),
    ]
