# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0015_mediumlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
