# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0016_medium_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumcontribution',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
