# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0017_auto_20160620_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inspiration.MediumType'),
            preserve_default=False,
        ),
    ]
