# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0020_auto_20160621_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='type',
        ),
    ]
