# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0023_insight_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='private',
            field=models.BooleanField(),
        ),
    ]
