# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0024_auto_20160630_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
