# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0026_auto_20160630_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insight',
            old_name='private',
            new_name='personal',
        ),
    ]
