# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0027_auto_20160701_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspiration.Medium'),
        ),
    ]
