# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0029_conversation_moment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='insight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='inspiration.Insight'),
        ),
    ]
