# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0030_moment_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='insight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='inspiration.Insight'),
        ),
        migrations.AddField(
            model_name='note',
            name='insight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inspiration.Insight'),
        ),
    ]
