# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0031_auto_20160704_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='title',
            field=models.CharField(default='asdfasdf', max_length=255),
            preserve_default=False,
        ),
    ]
