# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0033_auto_20160705_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momenttype',
            name='user',
        ),
    ]
