# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 04:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0034_remove_momenttype_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='submittion_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
