# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import inspiration.models.InspirationBaseModelMixin


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0035_moment_submittion_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, inspiration.models.InspirationBaseModelMixin.InspirationBaseModelMixIn),
        ),
        migrations.AlterField(
            model_name='moment',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='momenttag',
            name='moment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='inspiration.Moment'),
        ),
        migrations.AddField(
            model_name='momenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspiration.Tag'),
        ),
    ]
